# -*- coding: utf-8 -*-
"""Order Processor Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSxYm9MeE19jejf6lp6nOVF5DDLHHDii
"""

orders = [
    {
        "id": 5001,
        "customer": "Adil Safi",
        "email": "adil@gmail.com",
        "total": "7500.00",  # comes as string from Shopify
        "status": "paid",
        "country": "PK",
        "destination": "International",
        "is_new_customer": False,
        "items": ["Laptop Stand", "Mouse", "Keyboard"]
    },
    {
        "id": 5002,
        "customer": "Ahmed Khan",
        "email": "ahmed@gmail.com",
        "total": "95000.00",  # comes as string from Shopify
        "status": "paid",
        "country": "NG",
        "destination": "international",
        "is_new_customer": True,
        "items": ["Laptop", "Tablet"]
    },
    {
        "id": 5003,
        "customer": "Sara Ali",
        "email": "sara@gmail.com",
        "total": "2200.00",  # comes as string from Shopify
        "status": "pending",
        "country": "PK",
        "destination": "domestic",
        "is_new_customer": True,
        "items": ["T-Shirt", "Jeans"]
    },
    {
        "id": 5004,
        "customer": "Khan Baba",
        "email": "khan@gmail.com",
        "total": "4500.00",  # comes as string from Shopify
        "status": "paid",
        "country": "PK",
        "destination": "domestic",
        "is_new_customer": False,
        "items": ["Shoes", "Belt", "Cap"]
    },
    {
        "id": 5005,
        "customer": "Zara Ahmed",
        "email": "zara@gmail.com",
        "total": "55000.00",  # comes as string from Shopify
        "status": "paid",
        "country": "PK",
        "destination": "domestic",
        "is_new_customer": True,
        "items": ["iPhone", "AirPods"]
    }
]

high_risk_countries = ["NG", "KP", "MM"]
TAX_RATE = 0.17

pending_skipped_count = 0
fraud_flagged_count = 0
successfully_processed_count = 0
total_revenue = 0.0

print("======== Automated Order Processing ========\n")

# Processing Rules
for order in orders:
    current_fraud_count = False
    # step 1: Skipping Pending Orders:
    if order["status"] == "pending":
        print(f"Skipping order #{order['id']} - Pending")
        pending_skipped_count += 1
        continue
    # Step 2: Type conversion
    total = float(order["total"])
    # step 3: Fraud detection (Separate if statements):
    if order["country"] in high_risk_countries:
        print(f"🚨 Order #{order['id']} flagged: high risk country ({order['country']})")
        current_fraud_count = True
    if total > 50000 and order["is_new_customer"]:
        print(f"🚨 Order #{order['id']} flagged: high value new customer ({total})")
        current_fraud_count = True
    if current_fraud_count:
        fraud_flagged_count += 1
        continue
    # Step 4: Tax calculation:
    tax = round(total * TAX_RATE, 2)
    grand_total = total + tax
    total_revenue += grand_total
    successfully_processed_count += 1
    # Step 5: Shipping rules:
    shipping_cost = "Free"
    if order["destination"] == "international":
        shipping_cost = 1500
    if order["destination"] == "domestic" and total > 3000:
        shipping_cost = "Free"
    if order["destination"] == "domestic" and total <= 3000:
        shipping_cost = 300
    #step 6: Print order report:
    print(f"\n==============================")
    print(f"Order #{order["id"]}")
    print(f"Customer: {order["customer"]} ({order["email"]})")
    print(f"Items:")
    for index, item in enumerate(order["items"]):
        print(f"{index + 1}. {item}")
    print(f"Subtotal: {total} PKR")
    print(f"Tax (17%): {tax} PKR")
    print(f"Shipping: {shipping_cost}")
    print(f"Total: {grand_total} PKR")
    print("=================================")
# Step 7: Final summary after all orders:
print(f"\n===== FINAL SUMMARY ============")
print(f"📊 PROCESSING REPORT")
print(f"Total orders received: {len(orders)}")
print(f"Pending (skipped):     {pending_skipped_count}")
print(f"Flagged (fraud):       {fraud_flagged_count}")
print(f"Successfully processed: {successfully_processed_count}")
print(f"Total revenue:         {total_revenue} PKR")
print(f"=================================")

