# -*- coding: utf-8 -*-
"""robust_order_parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebpjwwkclKSdX21SNaVAKjBjI-5pu-AB
"""

# robust order parser:
# This takes a raw shopfiy order dictionary and return a clean, safe dictionary with 7 fields.
# step 1:- function
def robust_order_parser(raw, default = None):
    order_id = raw["id"]
    # Step 2: Try/except -- error catch blocks
    try:
        order_number =  raw["order_number"]
    except KeyError:
        order_number = "UNKNOWN"
    try:
        total =  float(raw["total_price"])
    except ValueError:
        total = 0.0
    try:
        customer_email = raw["customer"]["email"]
    except KeyError:
        customer_email = "no-email"
    try:
        status = raw["financial_status"]
    except KeyError:
        status = "unknown"
    try:
        first_sku = raw["line_items"][0]["sku"]
    except (IndexError, KeyError):
        first_sku = "NO_SKU"
    try:
        is_first_order = raw["customer"]["orders_count"] == 1
    except KeyError:
        is_first_order = False
    # step 3: return the clean dictionary with 7 fields
    return {
    "id": order_id,
    "order_number": order_number,
    "total": total,
    "customer_email": customer_email,
    "status": status,
    "first_sku": first_sku,
    "is_first_order": is_first_order
}
# Step 4: testing....
test_orders = [
    {
        "id": 5001,
        "order_number": "#5001",
        "total_price": "250.00",
        "financial_status": "paid",
        "customer": {"email": "adil@test.com", "orders_count": 1},
        "line_items": [{"sku": "WATCH-BLK", "quantity": 1}]
    },
    {
        "id": 5002,
        "order_number": "#5002",
        "total_price": "bad_value",
        "financial_status": "paid",
        "customer": {"email": "sara@test.com", "orders_count": 3},
        "line_items": [{"sku": "JEANS-BLU", "quantity": 2}]
    },
    {
        "id": 5003,
        "order_number": "#5003",
        "total_price": "180.00",
        "financial_status": "pending",
        "customer": {"orders_count": 1},
        "line_items": []
    },
    {
        "id": 5004,
        "order_number": "#5004",
        "total_price": "99.00",
        "financial_status": "paid",
        "customer": {"email": "khan@test.com"},
        "line_items": [{"quantity": 1}]
    }
]
# Step 5: Loop and printing the result
for order in test_orders:
    result = robust_order_parser(order)
    print(result)
# result:
#{'id': 5001, 'order_number': '#5001', 'total': 250.0, 'customer_email': 'adil@test.com', 'status': 'paid', 'first_sku': 'WATCH-BLK', 'is_first_order': True}
#{'id': 5002, 'order_number': '#5002', 'total': 0.0, 'customer_email': 'sara@test.com', 'status': 'paid', 'first_sku': 'JEANS-BLU', 'is_first_order': False}
#{'id': 5003, 'order_number': '#5003', 'total': 180.0, 'customer_email': 'no-email', 'status': 'pending', 'first_sku': 'NO_SKU', 'is_first_order': True}
#{'id': 5004, 'order_number': '#5004', 'total': 99.0, 'customer_email': 'khan@test.com', 'status': 'paid', 'first_sku': 'NO_SKU', 'is_first_order': False}
